# AI CITATION: This section of the assignment was generated by chat gpt
# prompt: please write a very basic make file to compile and run these files. It must work on linux.

CC = gcc

CFLAGS = -Wall -g 

SRC = filetree.c pa0_goosman.c utils.c

HEADERS = filetree.h utils.h

OUTPUT = a.exe

all: $(OUTPUT)

$(OUTPUT): $(SRC) $(HEADERS)
	$(CC) $(CFLAGS) -o $(OUTPUT) $(SRC)

clean:
	rm -f $(OUTPUT)

run: $(OUTPUT)
	./$(OUTPUT)
